### ISSUE TITLE
Standalone function

### ISSUE THREAD

**Issue by ilyakorsunsky** [Teichlab/bbknn#1]
Really exciting method! I don't usually usually use scanpy for my pipelines. Do you have a BBKNN function that works without it? Maybe something that takes in only PCs and batch labels?

**Comment by ktpolanski** [comment]
Thanks for the kind words! This sounds like a sensible thing to include, but I'd like to avoid doing it in an ad-hoc manner and take the opportunity to potentially refactor the code a bit. Meanwhile, enjoy this simple way of turning a PC matrix `pcs` (with cells as rows) and a list of per-cell batch labels `batchlist` into a BBKNN-ready AnnData object. The main results of interest will live in `adata.uns['neighbors']['connectivities']`.

```
import AnnData

adata = anndata.AnnData(obs=batchlist)
adata.obsm['X_pca'] = pcs
bbknn.bkknn(adata, batch_key=0)
```

**Comment by ilyakorsunsky** [comment]
Thanks that it super helpful!

**Comment by ktpolanski** [comment]
I have refactored the code and added `bbknn.bbknn_pca_matrix()`, which does exactly what you're after. You can collect version 1.2.0 from pip. Thanks for the suggestion!

**Comment by ilyakorsunsky** [comment]
Confirmed that it also works with reticulate in R. Thanks for doing this so fast!

library(reticulate)
use_python("~/miniconda3/bin/python")
bbknn <- import("bbknn")
bbknn_res <- bbknn$bbknn_pca_matrix(pca = pca_mat, batch_list = meta_data$batch)
