### ISSUE TITLE
Bandwidth parameter no longer supported by scanpy or UMAP

### ISSUE THREAD

**Issue by ivirshup** [Teichlab/bbknn#10]
This was originally reported by a scanpy user here: https://github.com/theislab/scanpy/issues/632.

Scanpy has just removed a frozen version of the `umap` library we'd been using (PR: https://github.com/theislab/scanpy/pull/576). The current version of umap doesn't support a bandwidth parameter, so now `compute_connectivities_umap` doesn't either. It looks like this is causing an issue with these lines, where bandwidth is explicitly passed:

https://github.com/Teichlab/bbknn/blob/93f25dc4914148ae00843f6166514ce379efff57/bbknn/__init__.py#L272-L274

Sorry about the break with so little notice!

**Comment by ktpolanski** [comment]
Thanks for the catch. Funny story, I just incidentally fixed this today while removing the scanpy dependency from `bbknn_pca_matrix`. I'll push out 1.3.2 to GitHub and pip today or tomorrow.

**Comment by ivirshup** [comment]
Ha, very useful coincidence! Glad to see we didn't break anything important.

Thanks for the quick response!

**Comment by zzwch** [comment]
when I run `sc.external.pp.bbknn(adata, batch_key='batch')` using scanpy 1.4.2 and bbknn 1.3.2 (upgrade to the latest), I get this error `bbknn_pca_matrix() got an unexpected keyword argument 'save_knn'`

**Comment by ktpolanski** [comment]
I took out knn saving as it didn't really serve a practical purpose. It was used for some visualisation in a demonstration notebook ages ago, but then the thing it was visualising got taken out of BBKNN a while ago. Were you actually using it for anything? If not, just take out `save_knn=True` from your call and you're good.

**Comment by zzwch** [comment]
got the same error using `sc.external.pp.bbknn(adata, batch_key='batch', save_knn=True)`

**Comment by ktpolanski** [comment]
I just told you I took out the parameter from the innards, you use a different wrapper and are surprised it yields the same result :P

**Comment by zzwch** [comment]
Clearly, I will use bbknn.bbknn instead.

import bbknn
bbknn.bbknn(adata, batch_key='batch')

**Comment by ktpolanski** [comment]
Huh, my bad, the scanpy function uses `save_knn` internally. Just import bbknn and call `bbknn.bbknn()` directly, that'll do it. I'll contact the scanpy folks about this.

**Comment by 1eesh** [comment]
I find your save_knn function extremely useful ! I am currently reverting to the 1.3.0 version of bbknn so I can use save_knn , but it would be nice to have the save_knn option in future versions of bbknn. @ktpolanski
