### ISSUE TITLE
Correcting for more than 1 covariate using BBKNN

### ISSUE THREAD

**Issue by dnehar** [Teichlab/bbknn#18]
Hi, 

Is there a way to correct for more than 2 covariates (e.g.  10X batches and donors) using BBKNN ? 
Also, thank you for this super helpfull tool !
Best,

**Comment by ktpolanski** [comment]
Just combine the two into a new `adata.obs` column. Assuming they're both strings, `adata.obs['combined'] = adata.obs['key1'] + adata.obs['key2']`.
