### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by mvfki** [Teichlab/bbknn#21]
A ModuleNotFoundError raised for me when I was trying `bbknn.bbknn(adata)` function, at `./bbknn/__init__.py` line 262, where you wrote 
```
start = logg.info(...)
```
I know that this `logg` came from line 10 
```
from scanpy import logging as logg
```
Here you are using a "try/except" syntax, such that you are allowing the nonexistence of `scanpy`. But in the core function (line 262) it seems still mandatory.  

Simply installing `scanpy` has already fixed it, I am just writing this down in case anyone else new to all these pipelines encounters a similar issue.

**Comment by ktpolanski** [comment]
Not a bug. `bbknn.bbknn()` operates on an AnnData object, so having scanpy around seems logical. `bbknn.bbknn_pca_matrix()`, on the other hand, does not use scanpy logging, and would work fine.
