### ISSUE TITLE
scanpy update incompatibility

### ISSUE THREAD

**Issue by bjstewart1** [Teichlab/bbknn#26]
calling bbknn either from scanpy.external (or bbknn direct) yields: 

`Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: 'tuple' object has no attribute 'tocsr' `

this is reported on scanpy https://github.com/theislab/scanpy/issues/1249 where the solution maybe is downgrading umap, but that's not ideal...

`umap-learn                0.4.3
bbknn                     1.3.4
scanpy                    1.5.1
anndata                   0.7.3`

Any ideas?

**Comment by ktpolanski** [comment]
Upgrade bbknn.

**Comment by ktpolanski** [comment]
The solution is instead upgrading bbknn. The exact fix needed has been introduced in 1.3.8.
