### ISSUE TITLE
Please also require packaging in setup.py

### ISSUE THREAD

**Issue by jenzopr** [Teichlab/bbknn#27]
Hi Krzysztof,

the bbknn bioconda build fails for current version `1.3.10` and `1.3.11` because the `packaging` package you introduced in d6c60f5e533ba6986b9d4ca4e94f0da9a699a9a6 cannot be found. I added it to the recipe dependencies, but I recommend adding it to `install_requires` as well.

Thanks,
Jens

**Comment by ktpolanski** [comment]
My apologies, all the python environments I've tested this in had this package installed, so I assumed it came bundled with python or something. Will do.

**Comment by ktpolanski** [comment]
Released as 1.3.12, thanks for bringing this to my attention. I'm actually curious which package fetched `packaging` along with it in all those cases.
