### ISSUE TITLE
bbknn spark error when runing with data integrated from scRNA data

### ISSUE THREAD

**Issue by honghh2018** [Teichlab/bbknn#29]
Hi @Teichlab,
     The weird condition occurred from data integrated through scanpy using bbknn.
      The samples can be integrated by umap plot, but the tsne plotting showing the data that can not be integrated.
     
![image](https://user-images.githubusercontent.com/41668708/90841674-c8634980-e38f-11ea-9169-cbaf83567628.png)
    UMAP showing integrated
    
![image](https://user-images.githubusercontent.com/41668708/90841695-da44ec80-e38f-11ea-932e-91b5cb84fc64.png)
  TSNE showing no integrated

      The different showing below between umap and tsne.
       Based on this, how can i get same integrated effect on tsne when using bbknn to integrated. if it should not been done,
       whether had another way to replace this selection?
  Best
  hanhuihong

**Comment by ktpolanski** [comment]
I'd like to defer you to the innards of [`sc.tl.tsne()`](https://github.com/theislab/scanpy/blob/master/scanpy/tools/_tsne.py), wherein you'll see that the TSNE operates in a manner independent of the neighbour graph. BBKNN's output isn't seen by the algorithm.
