### ISSUE TITLE
Details for pbmc dataset used

### ISSUE THREAD

**Issue by mohit1997** [Teichlab/bbknn#30]
Hi,

I am using the dataset mentioned in the notebook linked to this rep.
The link to download the data is [ftp://ngs.sanger.ac.uk/production/teichmann/BBKNN/PBMC.merged.h5ad](ftp://ngs.sanger.ac.uk/production/teichmann/BBKNN/PBMC.merged.h5ad)

Can you provide details about where the dataset is obtained (sequencing technologies and such)? Is there a publication from your group which explains this dataset?

**Comment by ktpolanski** [comment]
It's just some demo data pulled from the 10X website. From the original preprint:

"The input data was downloaded from the 10X Genomics website. The exact 5′dataset was ‘PBMCs of a healthy donor 5′gene expression’, under Cell Ranger 2.1.0, under V(D)J + 5′Gene Expression. The exact 3′dataset was ‘8k PBMCs from a Healthy Donor’, under Cell Ranger 2.1.0, under Chromium Demonstration (v2 Chemistry)."

**Comment by mohit1997** [comment]
Thanks for your quick reply! I am having trouble finding the 5' dataset on the 10X Genomics website. Is it no longer available? Can you point me to it?
