### ISSUE TITLE
TypeError: info() got an unexpected keyword argument 'r

### ISSUE THREAD

**Issue by AkiraNom** [Teichlab/bbknn#31]
Good afternoon,

I'm running on the pbmc notebook with python 3.7.7, Scanpy 1.5.1, bbknn 1.3.3. After running the bbknn, the following error message appeared. I tested the "sc.external.pp.bbknn," and the same message was shown. Updating the version to python 3.8.0, scanpy 1.6.0 did not work either. 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-188adc627705> in <module>
----> 1 bdata = bbknn.bbknn(adata,batch_key='Sample',copy=True)

~\Anaconda3\lib\site-packages\bbknn\__init__.py in bbknn(adata, batch_key, approx, metric, copy, **kwargs)
    259                 If ``True``, return a copy instead of writing to the supplied adata.
    260 	'''
--> 261         logg.info('computing batch balanced neighbors', r=True)
    262         adata = adata.copy() if copy else adata
    263         #basic sanity checks to begin

TypeError: info() got an unexpected keyword argument 'r'

Do you have any idea what causes this error? Thank you.

**Comment by ktpolanski** [comment]
Update bbknn. The fix to this was introduced  in 1.3.5.
