### ISSUE TITLE
`n_trees` is now `annoy_n_trees`

### ISSUE THREAD

**Issue by ghost** [Teichlab/bbknn#41]
Thanks for the great method! 

The change of `n_trees` to `annoy_n_trees` seems to have broken compatibility with scanpy's bbknn module (`sc.pp.external.bbknn`). Are there any plans to make changes to that module as well?

**Comment by ktpolanski** [comment]
Thanks for the heads up, I'll pull request in the up to date argument names. For now feel free to use `bbknn.bbknn()`, which `sc.external.pp.bbknn()` is just a wrapper for anyway.

**Comment by ghost** [comment]
Thank you!

**Comment by ktpolanski** [comment]
I opened a [pull request](https://github.com/theislab/scanpy/pull/1868) on the day, haven't heard back yet.
