### ISSUE TITLE
Removing multiple covariates during integration

### ISSUE THREAD

**Issue by connorhknight** [Teichlab/bbknn#46]
Hi, 

I was wondering if it is possible for bbknn to correct for more than one batch indicator. i.e. different projects and different donors. 

Thanks! 

Connor

**Comment by ktpolanski** [comment]
You could create a new `.obs` column which combines your multiple batch indicators and feed that in. Something along the lines of `adata.obs['bbknn_batch'] = [str(i)+'-'+str(j) for i,j in zip(adata.obs['project'], adata.obs['donor'])]` should do the trick.
