### ISSUE TITLE
Performace varied on different operating systems

### ISSUE THREAD

**Issue by cquzys** [Teichlab/bbknn#47]
Hello:
   When I installed bbknn 1.4.0 on ubuntu 16 and ubuntu 18, I got different performances on these two different operating systems. Concretely,  the cell similarity scores varied between batches when running bbknn on ubuntu 16 and 18.  Can you help me solve it?

Thank you very much!

**Comment by ktpolanski** [comment]
I wouldn't be surprised if something about the backend of the knn functions worked differently on different operating systems.

**Comment by cquzys** [comment]
Sorry, it seems that you know the problem. Can you tell me exactly which library or function is affected?  In my  opinion, it is likely that the annoy called by bbknn is affected by the GCC compiler. Thank you very much.
