### ISSUE TITLE
error during ridge_regression

### ISSUE THREAD

**Issue by JuliaChristiaanse** [Teichlab/bbknn#53]
Hi there,

First of all, thank you for this great package! It has been very helpful for my graduation project so far.
I am currently following the bbknn tutorial notebook, but I get an error at the ridge_regression part of the tutorial.
"AttributeError: module 'numpy' has no attribute 'int'." 

"`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20;""

I get this error when following your tutorial notebook with my own dataset. I am quite new to scRNAseq analysis and I am simply wondering if it's my package management that's wrong or that it might be something else?

Anyway, grateful in advance for your reply!

Greetings,

Julia

**Comment by ktpolanski** [comment]
It would appear that `np.int()` got removed in numpy 1.20.0. I've found the offending line and switched it to `int()` as pre the recommendation.

You can either downgrade numpy to a pre-1.20.0 version, or uninstall BBKNN and install it straight from GitHub with the change applied. There are a couple other tweaks in place which will at some point be released as 1.6.0, but it should work like your existing version.

**Comment by JuliaChristiaanse** [comment]
I tried with a numpy pre-1.20.0 version, but that did not solve the problem.
But updating the bbknn package worked like a charm :D
Thank you !
