### ISSUE TITLE
Update on bioconda

### ISSUE THREAD

**Issue by benjamin-james** [Teichlab/bbknn#59]
Hi, 

Can you update the recipe on bioconda? The bioconda version is still at 1.5.1

Thanks

**Comment by ktpolanski** [comment]
I wasn't the one who put it there, sorry.

**Comment by ktpolanski** [comment]
I found the conda recipe and tried updating it to 1.6.0. Let's see how the [PR](https://github.com/bioconda/bioconda-recipes/pull/44786) goes!
