### ISSUE TITLE
kernals died when using bbknn

### ISSUE THREAD

**Issue by FessenSimon** [Teichlab/bbknn#60]
I'm trying to do bbknn with my own single-cell data and demo data, but kernals died every time when I doing whatever my own data or demo data.
Is this because of my device? or?

sc.settings.verbosity = 3sc.logging.print_header()
sc.settings.set_figure_params(dpi=80)
scanpy==1.10.1 anndata==0.10.5.post1 umap==0.5.5 numpy==1.26.4 scipy==1.11.1 pandas==2.2.2 scikit-learn==1.3.0 statsmodels==0.14.0 igraph==0.11.5 louvain==0.8.2 pynndescent==0.5.11

adata = sc.read('pancreas.h5ad', backup_url='https://www.dropbox.com/s/qj1jlm9w10wmt0u/pancreas.h5ad?dl=1')
bbknn.bbknn(adata, batch_key='batch')

**Comment by ktpolanski** [comment]
It's almost certainly because of the package annoy. Try running bbknn with `computation="cKDTree"`.

Known ways to try to get annoy to cooperate is creating a fresh conda environment, or installing a different version from pip.

**Comment by FessenSimon** [comment]
Thank u! Now it's working well!
