### ISSUE TITLE
BBKNN for ATAC data

### ISSUE THREAD

**Issue by wlason** [Teichlab/bbknn#61]
Hi! Thank you for the awesome package :)
I was wondering if it is possible to use other dimensionality reduction methods than PCA for `bbknn.bbknn`, such as LSI which is commonly used for ATAC data? `use_rep` argument would suggest it is possible, but I wanted to check what your thoughts were before running it!

**Comment by ktpolanski** [comment]
Correct - just point `use_rep` to whatever you want to use from `.obsm`.
