### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by Silencewu7** [Teichlab/bbknn#63]
hi dear developer

I'm trying to install this package however fail with this error
`Failed to build installable wheels for some pyproject.toml based projects (annoy)`

I‘ve upgraded my pip and installed 'pyproject', but it still doesn't work. How should I deal with it.

**Comment by ktpolanski** [comment]
Try installing different versions of annoy. If nothing works, you have two options:
- Clone this GitHub repository, comment out the loading of the annoy in the source code and annoy as a dependency, install, and use non-annoy neighbour searches.
- Take this up with annoy devs as it's their package that's misbehaving.
