### ISSUE TITLE
install error with sklearn errors - both conda and pip

### ISSUE THREAD

**Issue by rcorbett-match** [Teichlab/bbknn#64]
Hi folks.

I'm trying to get bbknn running but ran in to some library errors at runtime.

I installed BBKNN using conda:
`conda install BBKNN`
and no errors or warnings were thrown.

Then when I try to import BBKNN using my conda python I see
```
ImportError                               Traceback (most recent call last)
Cell In[1], [line 2](vscode-notebook-cell:?execution_count=1&line=2)
      [1](vscode-notebook-cell:?execution_count=1&line=1) # try umapping and bbknn correcting to make a pre- and post-correction umap
----> [2](vscode-notebook-cell:?execution_count=1&line=2) import bbknn
      [4](vscode-notebook-cell:?execution_count=1&line=4) adata = sc.read_h5ad("all_process.h5ad")
      [5](vscode-notebook-cell:?execution_count=1&line=5) sc.pl.umap(adata, color=["majority_voting", "type", "FFPE_id"], size=2, ncols=1)

File ~/miniconda3/envs/scRNA_env/lib/python3.10/site-packages/bbknn/__init__.py:5
      [3](https://vscode-remote+ssh-002dremote-002bgphost09-002ebcgsc-002eca.vscode-resource.vscode-cdn.net/home/rcorbett/scRNA/~/miniconda3/envs/scRNA_env/lib/python3.10/site-packages/bbknn/__init__.py:3) from annoy import AnnoyIndex
      [4](https://vscode-remote+ssh-002dremote-002bgphost09-002ebcgsc-002eca.vscode-resource.vscode-cdn.net/home/rcorbett/scRNA/~/miniconda3/envs/scRNA_env/lib/python3.10/site-packages/bbknn/__init__.py:4) from sklearn.neighbors import KDTree
----> [5](https://vscode-remote+ssh-002dremote-002bgphost09-002ebcgsc-002eca.vscode-resource.vscode-cdn.net/home/rcorbett/scRNA/~/miniconda3/envs/scRNA_env/lib/python3.10/site-packages/bbknn/__init__.py:5) from sklearn.neighbors import DistanceMetric
      [6](https://vscode-remote+ssh-002dremote-002bgphost09-002ebcgsc-002eca.vscode-resource.vscode-cdn.net/home/rcorbett/scRNA/~/miniconda3/envs/scRNA_env/lib/python3.10/site-packages/bbknn/__init__.py:6) from scipy.spatial import cKDTree
      [7](https://vscode-remote+ssh-002dremote-002bgphost09-002ebcgsc-002eca.vscode-resource.vscode-cdn.net/home/rcorbett/scRNA/~/miniconda3/envs/scRNA_env/lib/python3.10/site-packages/bbknn/__init__.py:7) from scipy.sparse import coo_matrix

ImportError: cannot import name 'DistanceMetric' from 'sklearn.neighbors' (/home/rcorbett/miniconda3/envs/scRNA_env/lib/python3.10/site-packages/sklearn/neighbors/__init__.py)
```

So then I try to install with pip as I saw your issue saying this error was fixed in a pip release last year.   However, with pip I get this error:
```
pip install bbknn
Requirement already satisfied: bbknn in /home/rcorbett/miniconda3/envs/scRNA_env/lib/python3.10/site-packages (1.3.3)
Requirement already satisfied: Cython in /home/rcorbett/miniconda3/envs/scRNA_env/lib/python3.10/site-packages (from bbknn) (3.0.11)
Requirement already satisfied: numpy in /home/rcorbett/miniconda3/envs/scRNA_env/lib/python3.10/site-packages (from bbknn) (1.26.4)
Requirement already satisfied: scipy in /home/rcorbett/miniconda3/envs/scRNA_env/lib/python3.10/site-packages (from bbknn) (1.14.1)
Requirement already satisfied: annoy in /home/rcorbett/miniconda3/envs/scRNA_env/lib/python3.10/site-packages (from bbknn) (1.17.3)
Requirement already satisfied: umap-learn in /home/rcorbett/miniconda3/envs/scRNA_env/lib/python3.10/site-packages (from bbknn) (0.5.7)
Collecting sklearn (from bbknn)
  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Can you point me in the right direction?
thanks
Richard

**Comment by ktpolanski** [comment]
Cannot replicate.

Created fresh conda environment, installed bbknn in it:
```python
conda create --name bbknntest python=3.10
conda activate bbknntest
conda install bbknn
```
This pulled in bbknn 1.6.0 and sklearn 1.5.2 and everything loads fine.

Created second fresh conda environment and installed via pip:
```python
conda create --name bbknntest2 python=3.10
conda activate bbknntest2
pip install bbknn
```
This also pulled in bbknn 1.6.0 and sklearn 1.5.2, just from a different source.

My `~/.condarc` in case it matters:
```
env_prompt: ({name})
channels:
  - conda-forge
  - bioconda
  - nodefaults
envs_dirs:
  - /home/jovyan/my-conda-envs/
create_default_packages:
  - pip
  - ipykernel
denylist_channels: [defaults, anaconda, r, main, pro] #!final
```

I'd like to direct you to `Requirement already satisfied: bbknn in /home/rcorbett/miniconda3/envs/scRNA_env/lib/python3.10/site-packages (1.3.3)` in your pip paste. You're not actually installing a new bbknn with that syntax, and back during the days of 1.3.3 bbknn did actually [depend on the now-deprecated sklearn](https://github.com/Teichlab/bbknn/blob/0eae34a2a373d7f9d5f710b931f93b3a0e96c78d/setup.py#L9)

**Comment by ktpolanski** [comment]
```
Requirement already satisfied: bbknn in /home/rcorbett/miniconda3/envs/scRNA_env/lib/python3.10/site-packages (1.3.3)
```

That's because you've got 1.3.3 installed and you're not actually installing a new one with your syntax. The import error in the first one refers to [a line in a file that's no longer there](https://github.com/Teichlab/bbknn/blob/0eae34a2a373d7f9d5f710b931f93b3a0e96c78d/bbknn/__init__.py#L5) (compare to the [current line 5 of the file](https://github.com/Teichlab/bbknn/blob/95ce34b8905cbde307704a77436c354938ba0367/bbknn/__init__.py#L5)). And yes, back in 1.3.3 days bbknn depended on the [now-deprecated sklearn](https://github.com/Teichlab/bbknn/blob/0eae34a2a373d7f9d5f710b931f93b3a0e96c78d/setup.py#L9).

For pip, to update an existing package you do `pip install --upgrade`. I don't know the conda syntax off hand. If you want to keep your existing old 1.3.3 bbknn, make sure your scipy is below 1.6.0 and your scikit-learn is below 1.0.2.

**Comment by rcorbett-match** [comment]
Nice. Thank you.   This was a fresh conda environment started a couple of days ago. I wonder if perhaps scanpy autoinstalled the old version?    Will try the upgrade now.  Thx!

**Comment by ktpolanski** [comment]
I tend to use conda to set up the environment and then pip in as much as possible. So make a fresh one and install both scanpy and bkknn from pip and see how you get along.

**Comment by zzz992** [comment]
Have you solved it? I had the same problem.

**Comment by MJ-Yang** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2024-12-23T16:21:16
          
          
            * 메일 제목 : 
Re: [Teichlab/bbknn] install error with sklearn errors - both conda and pip (Issue #64)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.
