### ISSUE TITLE
bbknn.bbknn_pca_matrix() output is different from that of bbknn.bbknn()

### ISSUE THREAD

**Issue by NikTuzov** [Teichlab/bbknn#9]
Are differences expected? If not, I can attach the code and data.

**Comment by NikTuzov** [comment]
In addition, I decided to check whether the visualization is the same. I populated "distances" and "connectivities" in AnnData object by the values generated by bbknn_pca_matrix() and then ran UMAP on the AnnData object. The visualization is very different from the one obtained when bbknn() is applied to AnnData object.

**Comment by ktpolanski** [comment]
`bbknn.bbknn()` is just a wrapper for `bbknn.bbknn_pca_matrix()`.

https://github.com/Teichlab/bbknn/blob/93f25dc4914148ae00843f6166514ce379efff57/bbknn/__init__.py#L214-L217

**Comment by NikTuzov** [comment]
Hello Krzysztof:

Thanks for replying. Apparently, I did something wrong if I got a different UMAP result. I'll take a look at your reference to figure that out.

Regards,
Nik
